version: '3'

services:
  slug-api:
    image: bitnami/postgresql
    container_name: slug-api
    ports:     
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=db-api